site_name: Escritório RSMDG Advogados Associados
nav:
  - Home: index.md
extra_css:
  - css/extra.css  # Ensure this path matches your actual folder structure
theme:
  name: swan
  custom_dir: theme/
  favicon: images/favicon.ico
  logo: images/logo.png
  logo_cern: images/logo_cern.png

markdown_extensions:
  - toc:
      permalink: false

use_directory_urls: false


# mkdocs serve